### ISSUE TITLE
Bad link on website "Portallösungen & Services"

### ISSUE THREAD

**Issue by RainerBielefeld** [wechange-eg/cosinnus-core#341] opened 2023-08-08 07:36 UTC
STR:

1. Visit "[Portallösungen & Services](https://wechange.de/cms/portalloesungen-und-services/)"
2. Scroll down to field "Onlineportal für Organisationen, Vereine und Verbände"
3. Below "Referenzen:" check link(s) behind "plattform n"
    Expected: click on any letter of the string leads to https://plattform-n.org/group/forum-plattform-n/
   Actual:   
   a) strange view: "p" is not underlined, seems to be without hyperlink?  😥
   b) Click on letters in "plat" will lead to not existing https://plattform-n.org/n/     😥

Click on letters in "tform n" leads to existing https://plattform-n.org/group/forum-plattform-n/     👌

**Comment by mko-x** [comment] 2023-08-22 13:41
Hello @RainerBielefeld ,

thank you very much. The issue is now fixed and the fix is live.

**Closed by mko-x** 2023-08-22 13:41 UTC
